services:
  keydb:
    image: eqalpha/keydb
    command: ["keydb-server", "/etc/keydb/keydb.conf", "--server-threads", "3"]
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    networks:
      - payment-processor
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["python", "-m", "backend"]
    environment:
      - KEYDB_URL=redis://keydb:6379
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "125MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - payment-processor

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["python", "-m", "worker"]
    environment:
      - KEYDB_URL=redis://keydb:6379
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
      - WORKER_POOL_SIZE=250
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "125MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
