services:
  keydb:
    image: eqalpha/keydb
    command: [
      "keydb-server",
      "/etc/keydb/keydb.conf",
      "--server-threads", "3"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"
    ports:
      - "6379:6379"
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 2s
      retries: 3

  worker:
    image: lsfratel/rinha-2025-python:latest
    command: [
      "python", "bin/worker.py",
      "tasks.payments.huey",
      "-k", "greenlet",
      "-w", "30",
      "-n", "-C",
      "-q"
    ]
    environment:
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "100MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor

  api01:
    image: lsfratel/rinha-2025-python:latest
    command: [
      "python",
      "-m", "backend"
    ]
    environment:
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/payments-summary"]
      interval: 2s
      retries: 3

  api02:
    image: lsfratel/rinha-2025-python:latest
    command: [
      "python",
      "-m", "backend"
    ]
    environment:
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/payments-summary"]
      interval: 2s
      retries: 3

  lighttpd:
    image: jitesoft/lighttpd
    volumes:
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '30MB'
    networks:
      - default
      - payment-processor

networks:
  default:
    driver: bridge
  payment-processor:
    external: true
