services:
  keydb:
    image: eqalpha/keydb
    command: ["keydb-server", "/etc/keydb/keydb.conf", "--server-threads", "3"]
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 5s
      retries: 3

  backend1:
    image: lsfratel/rinha-2025-python:7
    command: ["python", "-m", "backend"]
    environment:
      - KEYDB_URL=redis://keydb:6379
      - UNIX_SOCKET=/sockets/backend1.sock
    volumes:
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "60MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "nc", "-zU", "/sockets/backend1.sock"]
      interval: 5s
      retries: 3

  backend2:
    image: lsfratel/rinha-2025-python:7
    command: ["python", "-m", "backend"]
    environment:
      - KEYDB_URL=redis://keydb:6379
      - UNIX_SOCKET=/sockets/backend2.sock
    volumes:
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "60MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor
    healthcheck:
      test: ["CMD", "nc", "-zU", "/sockets/backend2.sock"]
      interval: 5s
      retries: 3

  worker:
    image: lsfratel/rinha-2025-python:7
    command: ["python", "-m", "worker"]
    environment:
      - KEYDB_URL=redis://keydb:6379
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080
      - FALLBAK_PAYMENT_URL=http://payment-processor-fallback:8080
      - NUM_WORKERS=50
      - BACKOFF_FACTOR=0.2
      - NUM_OF_RETRY=7
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "120MB"
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - default
      - payment-processor

  lighttpd:
    image: jitesoft/lighttpd
    volumes:
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
      - sockets:/sockets:rw
    ports:
      - "9999:9999"
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
    networks:
      - default
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "40MB"

volumes:
  sockets:

networks:
  default:
    driver: bridge
  payment-processor:
    external: true
